{ TvCodePg: translation between a single-byte DOS code page and Unicode.

  Translated from magiblot/tvision @ b4831e2:
    source/platform/codepage.cpp (CpTranslator)
  The tables are generated by tools/gen-codepage.py (see tvcp.inc). Borland
  disclaimer and MIT notice: tv/COPYRIGHT.magiblot.

  Bytes that are not valid UTF-8 are shown through the current code page. The
  control characters 0..31 and 7Fh are shown as the IBM PC graphic symbols. The
  default page is 866 (tv/DESIGN.md, rule 5); magiblot's default is 437. }
unit TvCodePg;

{$I tvdefs.inc}

interface

const
  cpIdCp437 = 437;
  cpIdCp866 = 866;

{ Selects the current code page; False if the page is not known. }
function CpSelect(Id: Integer): Boolean;
function CpCurrent: Integer;

{ Code point displayed for byte B in the current page. }
function CpToUnicode(B: Byte): LongWord;
{ Byte for a code point, or 0 if the page has no such character. }
function CpFromUnicode(CodePoint: LongWord): Byte;
{ UTF-8 of CpToUnicode(B) written to Buf (4 bytes at least); returns its length. }
function CpToUtf8(B: Byte; Buf: PByte): Integer;

implementation

uses
  TvUtf8;

{$I tvcp.inc}

type
  PCpTable = ^TCpTable;
  TCpTable = array[0..255] of Word;

var
  Current: Integer = cpIdCp866;
  Table: PCpTable = @Cp866;
  { reverse map, sorted by code point: Rev[I] = code point, RevByte[I] = byte }
  Rev: array[0..255] of LongWord;
  RevByte: array[0..255] of Byte;

procedure BuildReverse;
var
  I, J: Integer;
  CP: LongWord;
  B: Byte;
begin
  for I := 0 to 255 do
  begin
    Rev[I] := Table^[I];
    RevByte[I] := I;
  end;
  { insertion sort; for equal code points the lowest byte comes first }
  for I := 1 to 255 do
  begin
    CP := Rev[I];
    B := RevByte[I];
    J := I - 1;
    while (J >= 0) and (Rev[J] > CP) do
    begin
      Rev[J + 1] := Rev[J];
      RevByte[J + 1] := RevByte[J];
      Dec(J);
    end;
    Rev[J + 1] := CP;
    RevByte[J + 1] := B;
  end;
end;

function CpSelect(Id: Integer): Boolean;
begin
  Result := True;
  case Id of
    cpIdCp437: Table := @Cp437;
    cpIdCp866: Table := @Cp866;
  else
    Exit(False);
  end;
  Current := Id;
  BuildReverse;
end;

function CpCurrent: Integer;
begin
  Result := Current;
end;

function CpToUnicode(B: Byte): LongWord;
begin
  Result := Table^[B];
end;

function CpFromUnicode(CodePoint: LongWord): Byte;
var
  Lo, Hi, Mid: Integer;
begin
  Lo := 0;
  Hi := 255;
  while Lo < Hi do
  begin
    Mid := (Lo + Hi) shr 1;
    if Rev[Mid] < CodePoint then
      Lo := Mid + 1
    else
      Hi := Mid;
  end;
  if Rev[Lo] = CodePoint then
    Result := RevByte[Lo]
  else
    Result := 0;
end;

function CpToUtf8(B: Byte; Buf: PByte): Integer;
begin
  Result := Utf8Encode(Table^[B], Buf);
end;

initialization
  BuildReverse;
end.
